// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg5aTYNcpPFwIWZBFGqLzaczkzwk7DOKY',
    appId: '1:60633949108:web:26208876a5a0b8cadf08e1',
    messagingSenderId: '60633949108',
    projectId: 'social-runwayclub',
    authDomain: 'social-runwayclub.firebaseapp.com',
    storageBucket: 'social-runwayclub.appspot.com',
    measurementId: 'G-2MS0VDE5YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi5ZxiCzwm9q87ay8s5YzglouGGBDnq5U',
    appId: '1:60633949108:android:0abcb0bb299dca23df08e1',
    messagingSenderId: '60633949108',
    projectId: 'social-runwayclub',
    storageBucket: 'social-runwayclub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9qnRXYVeLJxUBHMUPwk2fo0QbS-n7CM',
    appId: '1:60633949108:ios:d391977d1d75a66adf08e1',
    messagingSenderId: '60633949108',
    projectId: 'social-runwayclub',
    storageBucket: 'social-runwayclub.appspot.com',
    iosBundleId: 'com.runwayclub.socialRunway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ9qnRXYVeLJxUBHMUPwk2fo0QbS-n7CM',
    appId: '1:60633949108:ios:a9062aecb48dfbaddf08e1',
    messagingSenderId: '60633949108',
    projectId: 'social-runwayclub',
    storageBucket: 'social-runwayclub.appspot.com',
    iosBundleId: 'com.runwayclub.socialRunway.RunnerTests',
  );
}
